import type { Metadata } from 'next';
import { Baloo_Paaji_2 } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';

const balooPaaji2 = Baloo_Paaji_2({
  variable: '--font-baloo-paaji-2',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'heey studio',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${balooPaaji2.variable} antialiased`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
